AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Architectures:
      - arm64

Parameters:
  RssFeedUrl:
    Type: String
    Default: 'https://example.com/feed.xml'
  S3BucketName:
    Type: String
  S3Path:
    Type: String
    Default: 'ikizulive-posts'
  NotifySnsTopicArn:
    Type: String

Resources:
  IkizulivePostsSaveFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: IkizulivePostsSave
      CodeUri: function/
      Handler: app.lambda_handler
      Runtime: ruby3.3
      Timeout: 120
      MemorySize: 128
      Environment:
        Variables:
          RSS_FEED_URL: !Ref RssFeedUrl
          S3_BUCKET: !Ref S3BucketName
          S3_PATH: !Ref S3Path
          SNS_TOPIC_ARN: !Ref NotifySnsTopicArn
      Policies:
        - S3WritePolicy:
            BucketName: !Ref S3BucketName
        - SNSPublishMessagePolicy:
            TopicName: !Select [5, !Split [':', !Ref NotifySnsTopicArn]]
      Events:
        DailySchedule:
          Type: Schedule
          Properties:
            Name: IkizulivePostsSaveDailySchedule
            Schedule: cron(30 15 * * ? *)
            Description: 'いきづらい部！ ポスト保存（毎日0:30 JST）'
            Enabled: true
