AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Architectures:
      - arm64

Parameters:
  RssFeedUrl:
    Type: String
  S3BucketName:
    Type: String
  S3Path:
    Type: String
    Default: 'ikizulive-posts'
  NotifySnsTopicArn:
    Type: String

Resources:
  IkizulivePostsSaveFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ikizulive-posts-save
      CodeUri: function/
      Handler: app.lambda_handler
      Runtime: ruby3.4
      Timeout: 120
      MemorySize: 128
      Environment:
        Variables:
          RSS_FEED_URL: !Ref RssFeedUrl
          S3_BUCKET: !Ref S3BucketName
          S3_PATH: !Ref S3Path
          SNS_TOPIC_ARN: !Ref NotifySnsTopicArn
      Policies:
        - S3WritePolicy:
            BucketName: !Ref S3BucketName
        - Statement:
            - Effect: Allow
              Action:
                - sns:Publish
              Resource: !Ref NotifySnsTopicArn
      Events:
        Schedule:
          Type: Schedule
          Properties:
            Name: ikizulive-posts-save-schedule
            Schedule: cron(30 15 * * ? *)
            Description: 'いきづらい部！ メンバーポスト保存（毎日0:30 JST）'
            Enabled: true
