AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  hasu-dashboard-batch

Parameters:
  YoutubeApiKeyParameterName:
    Type: String
  BucketApiTokenParameterName:
    Type: String
  ParameterRegion:
    Type: String
  BucketName:
    Type: String

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60
    MemorySize: 128

Resources:
  GetContentsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: get_contents/
      Handler: app.lambda_handler
      Runtime: ruby3.3
      Architectures:
        - arm64
      Environment:
        Variables:
          YOUTUBE_API_KEY_PARAMETER_NAME: !Ref YoutubeApiKeyParameterName
          BUCKET_API_TOKEN_PARAMETER_NAME: !Ref BucketApiTokenParameterName
          PARAMETER_REGION: !Ref ParameterRegion
          BUCKET_NAME: !Ref BucketName
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: !Ref YoutubeApiKeyParameterName
        - SSMParameterReadPolicy:
            ParameterName: !Ref BucketApiTokenParameterName

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  GetContentsFunctionFunction:
    Description: 'Hasu Dashboard Batch Get Contents Function ARN'
    Value: !GetAtt GetContentsFunction.Arn
  GetContentsFunctionIamRole:
    Description: 'Implicit IAM Role created for Hasu Dashboard Batch Get Contents function'
    Value: !GetAtt GetContentsFunctionRole.Arn
